language: node_js
node_js:
- '6.1'
services:
- mongodb
notifications:
  email: false
  slack:
    secure: E5YmROp5NutcYnp3MuKwaZIFtIokGoANEbgLnbirpsdeWjZGe5R2LVSWdZKdMKYTzo7RHFEkkBLvJF9uBl0gq7755bn33bkChJm4bGX0+jQx7wHnAlq5n1weSOYt6iS4ETu9e+3DzrThUZ0oFgtxO2tFdm2amqI4zrO2Nn28oIqKjHfzPvmZXQ0om5bTw7YqSDVImpEjxtL4UUuukg4iacSJjSesqeMJKW5ToX5DB4y65N9oMoSFvXIJJpJmoJRjGAtolHFZb8rzQG7G9RTox/vitrag6kIp6ZcLwjpjpS1wSYaJQtQHchGCiKgabJoHvGGXpRfvtRjBWb3HwLh4fn2M5XC5sWnXpCJesg0p34fED3dSBxj4Vagg91wn28r5ZiG5h6hIeIazIQf4WsWYRnqhmzzOIt3NHFE5h2DngiOdGQfS4lvgROBdT/TROHDpnslWdS3Dj7RKGiXlGhY89xTF7/x/4PYVCIVuC8SXDpk0VT/SHdaqu6hb/Y97t5E6yZo42RycgvwuAdEuMT+/A8AnCrDs2krlH1+DW5b3g4DIbEGGsNdh0xf0QEgDHxMSc78dXA73ik4quUH+1RtsRLWX7roE9BKyZ1pJdkN/yd8+J2dAzYzllnblSMiu6lLChCqCvk/qWtTgc7/dXiNJ3nnYgcYmIr5eKp3SZI3kkSU=
